name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: workflow_dispatch
jobs: 
  print: 
    runs-on: ubuntu-latest
    steps:
      - name: Print to conosole
        run: echo Hello GH actions!!
